### ISSUE TITLE
Figure out how event refreshing works

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1167]

**Comment by Raijinili** [comment]
Some notes (using PST to indicate NA server time):
- Usually up some hours before daily refresh 1 (0:00 PST). I feel like it's kind of organic, though, happening inconsistently. I used to try to log in around that period to get the original limited_bonus_data, which can have errors fixed the next day.
- Check again before 6 AM or 7 AM PST, before the first event can start. (There's a minimum starting time for LTDs, but I don't remember whether it's 10 EST or 10 EDT.)
- They sometimes make mistakes. Remember the 0-stam EKMD which was not 0-stam, and had to be fixed after it started? There are probably also errors which get caught before that. I suspect (and hope) these missing SSGs is one of those mistakes, rather than a change in policy on when to update them.

**Comment by Raijinili** [comment]
The `ver` values also come in if you pass `&upd=y` in the `action=login` request. Doing `action=get_player_data` is unnecessary.

```py
{"res": 0,
"id": <PID>,
"sid": <SID>,
"time": "210611165641",  #login time?
"rlb": "120228040000",  #2012-02-28 04:00:00

# Data versions:
"cver": 607,
"sver": 413,
"dver": 469,
"pver": 2479,
"msver": 408,
"dsver": 138,
"psver": 145,
"alver": 38,
"mever": 174,
"tlver": 2,

# Probably personal info:
"mails": 177,
"rdun": null,
"tli": 0}
```
