### ISSUE TITLE
Upload new emoji

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1781]
* 9 new awakenings (6 of which are flavors of oe)
* also the balanced typing change, upload that one (that's from last patch but it's missing)
* add `_super` to the end of the existing names for them all in their non-super version
* for sb latent, call it :latent_sb_super:
* and upload the arlatent for FUA too, call it like latent_cloud_tape_clear or something
* once the latents are uploaded, update `^arlat` and `^arlatents` commands
* make a comment here with the names of all of the emojis so Aradia can update the new awakenings in code

**Comment by kary5678** [comment]
Uploaded latent_cloud_tape_clear, latent_sb_super

Balanced typing change awakening is actually not missing, it's just called add_type_balance instead of balanced.
Names of the other ones (were already uploaded):
misc_tpa_super
misc_skillcharge_super
oe_fire_super
oe_water_super
oe_wood_super
oe_light_super
oe_dark_super
oe_heart_super
